apiVersion: v1
kind: Service
metadata:
  name: data-agreement
  labels:
    app: agreement
    tier: backend
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  data-agreement-mapping
      prefix: /data-agreement/
      service: data-agreement
      rewrite: /data-agreement/
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  data-agreement-mapping
      prefix: /subscriptions
      service: data-agreement
      rewrite: /subscriptions      

spec:
  selector:
    app: agreement
    tier: backend
  ports:
    - port: 80
      name: http-vendor
      targetPort: http-vendor

